### PR TITLE
Add view latest version support from package.json file and script for quick testing

### PR DESCRIPTION
**Pull request by sadiqhabib**
Add view latest version support from package.json file and script for quick testing

### CODE REVIEW

**Review by ahmadassaf — APPROVED** [review]
great addition ! thanks

**Comment by sadiqhabib** [comment]
Your are welcome you can also close now #5 as well

**Comment by ahmadassaf** [comment]
already did :) thanks

**Comment by sadiqhabib** [comment]
I have one problem in cmd gitignore option is not working .

**Comment by ahmadassaf** [comment]
can you elaborate more ? what argument are you passing and what are the contents of your `gitignore` file .. and what is happening ?

**Comment by sadiqhabib** [comment]
See my `test:clean` script command or run `npm run test:clean` in cmd it is also looking inside `node_modules` as well

**Comment by ahmadassaf** [comment]
have you tried the `-g` instead ?

**Comment by ahmadassaf** [comment]
sorry i cannot test it now as i am not on a laptop .. browsing from phone ATM

**Comment by sadiqhabib** [comment]
Yeah both are making same problem. and i am getting all messages even from ignored dirs too

**Comment by ahmadassaf** [comment]
am not really sure whats happening but i believe its about the path to the `.gitignore` and maybe how you are calling the command. What i think is happening is that it tries to find the path relative to `bin/path` .. cannot confirm until i test

**Comment by sadiqhabib** [comment]
I tested even global installed version still getting notes from ignored files with this command `notes -g .gitignore` no path just navigate to project dir and run this but still it is making problem

**Comment by ahmadassaf** [comment]
have you tried doing `notes -g ./.gitignore`

**Comment by sadiqhabib** [comment]
Yes same problem

**Pull request merged**
